CREATE TABLE demandas_tb (
    id_demanda INT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(100) DEFAULT NULL,
    TIPO VARCHAR(50) DEFAULT NULL,
    DESCRICAO TEXT,
    DATA_INICIO DATETIME DEFAULT NULL,
    DATA_FIM_P DATETIME DEFAULT NULL,
    DATA_FIM_R DATETIME DEFAULT NULL,
    PRIORIDADE VARCHAR(50) DEFAULT NULL,
    STATUS VARCHAR(50) DEFAULT NULL,
    SEGMENTO VARCHAR(50) DEFAULT NULL,
    SEGMENTO_DETALHE VARCHAR(100) DEFAULT NULL,
    DATA_CRIACAO DATETIME DEFAULT NULL,
    CRIADOR_DEMANDA VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (id_demanda)
);