CREATE TABLE responsaveis_tb (
    id_responsavel INT NOT NULL AUTO_INCREMENT,
    NOME_COMPLETO VARCHAR(100) DEFAULT NULL,
    EMAIL VARCHAR(100) DEFAULT NULL,
    LOGIN VARCHAR(50) DEFAULT NULL,
    ATUACAO VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (id_responsavel)
);